name: duet_application
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  cloud_firestore: ^5.6.3
  firebase_app_check: ^0.3.2+2
  firebase_auth: ^5.4.2
  firebase_core: ^3.11.0
  firebase_data_connect: ^0.1.3
  firebase_storage: ^12.4.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
