// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUOMjISheNdFw3HfyxiZmcLEpYQgm5Jjk',
    appId: '1:734733104799:web:a337bdfc20c2fc3f5094aa',
    messagingSenderId: '734733104799',
    projectId: 'duet-5f08d',
    authDomain: 'duet-5f08d.firebaseapp.com',
    storageBucket: 'duet-5f08d.firebasestorage.app',
    measurementId: 'G-W0S8BZH20B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW1PHpSUGmrRVYUKLTcswiHsVgN1baD-A',
    appId: '1:734733104799:android:55d45b66cc45c7f85094aa',
    messagingSenderId: '734733104799',
    projectId: 'duet-5f08d',
    storageBucket: 'duet-5f08d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_zpfnWIGSr3xxTNCIh7nhIbikSxDTEPg',
    appId: '1:734733104799:ios:08b6c4772b0793cc5094aa',
    messagingSenderId: '734733104799',
    projectId: 'duet-5f08d',
    storageBucket: 'duet-5f08d.firebasestorage.app',
    iosBundleId: 'com.example.duetApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_zpfnWIGSr3xxTNCIh7nhIbikSxDTEPg',
    appId: '1:734733104799:ios:08b6c4772b0793cc5094aa',
    messagingSenderId: '734733104799',
    projectId: 'duet-5f08d',
    storageBucket: 'duet-5f08d.firebasestorage.app',
    iosBundleId: 'com.example.duetApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUOMjISheNdFw3HfyxiZmcLEpYQgm5Jjk',
    appId: '1:734733104799:web:593f3ca020b8366a5094aa',
    messagingSenderId: '734733104799',
    projectId: 'duet-5f08d',
    authDomain: 'duet-5f08d.firebaseapp.com',
    storageBucket: 'duet-5f08d.firebasestorage.app',
    measurementId: 'G-SQG5BT7XMH',
  );

}