import 'package:flutter/material.dart';
import 'package:flutter_dotenv/flutter_dotenv.dart';
import 'src/backend/spotifyUserData.dart';
import 'package:firebase_core/firebase_core.dart';
import 'firebase_options.dart'; // Generated by the FlutterFire CLI

Future<void> main() async {
  WidgetsFlutterBinding.ensureInitialized();
  // Load environment variables from a .env file.
  await dotenv.load(fileName: ".env");
  // Initialize Firebase.
  await Firebase.initializeApp(
    options: DefaultFirebaseOptions.currentPlatform,
  );
  runApp(MyApp());
}

class MyApp extends StatelessWidget {
  // Replace with a unique identifier in your actual app.
  static const String uuid = "user1234";

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Spotify Auth Web Example',
      home: Scaffold(
        appBar: AppBar(
          title: Text('Spotify Auth Web Example'),
        ),
        body: Center(
          child: SpotifyAuthWidget(),
        ),
      ),
    );
  }
}

class SpotifyAuthWidget extends StatefulWidget {
  @override
  _SpotifyAuthWidgetState createState() => _SpotifyAuthWidgetState();
}

class _SpotifyAuthWidgetState extends State<SpotifyAuthWidget> {
  bool _isLoading = false;
  SpotifyUserData? _spotifyUserData;
  String? _errorMessage;

  @override
  void initState() {
    super.initState();
    // On a reload after redirection from Spotify, attempt to create the profile.
    _attemptToGetUserProfile();
  }

  Future<void> _attemptToGetUserProfile() async {
    setState(() {
      _isLoading = true;
      _errorMessage = null;
    });
    try {
      // For demonstration, we use a static UUID.
      _spotifyUserData = await SpotifyUserData.createSpotifyProfile("user1234");
      setState(() {});
      debugPrint("Got Spotify user: ${_spotifyUserData!.username}");
    } catch (e) {
      // The auth flow will redirect the browser.
      // If an error occurs here (or if we are in the redirect branch),
      // you can choose to show an error message or simply ignore it.
      setState(() {
        _errorMessage = e.toString();
      });
    } finally {
      setState(() {
        _isLoading = false;
      });
    }
  }

  void _handleSignIn() async {
    await _attemptToGetUserProfile();
  }

  @override
  Widget build(BuildContext context) {
    if (_isLoading) {
      return CircularProgressIndicator();
    }
    if (_spotifyUserData != null) {
      // Display the Spotify user profile details from Firestore.
      return Column(
        mainAxisAlignment: MainAxisAlignment.center,
        children: [
          Text('Username: ${_spotifyUserData!.username}'),
          Text('Email: ${_spotifyUserData!.email}'),
          ElevatedButton(
            onPressed: () async {
              // Refresh data from Spotify and update Firestore.
              await _spotifyUserData!.updateSpotifyData();
              setState(() {});
            },
            child: Text('Refresh Spotify Data'),
          ),
        ],
      );
    }
    return Column(
      mainAxisAlignment: MainAxisAlignment.center,
      children: [
        if (_errorMessage != null) Text("Error: $_errorMessage"),
        ElevatedButton(
          onPressed: _handleSignIn,
          child: Text('Connect with Spotify'),
        ),
      ],
    );
  }
}
