name: Unit Tests Check

on:
  push: 
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
    - name: Clone branch
      uses: actions/checkout@v4

    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with: 
        channel: stable
        flutter-version: 3.27.3
        cache: true
      
    - name: Check flutter version and run Unit Tests 
      working-directory: ./duet_application
      run: 
        flutter --version;
        flutter test;