name: Web Build Check

on:
  push: 
    branches: [ "main", "integration" ]

  pull_request:
    branches: [ "main", "integration" ]

jobs:
  build:
    name: Test Web Build
    runs-on: ubuntu-latest
    steps:
    - name: Clone branch
      uses: actions/checkout@v4

    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle

    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with: 
        channel: stable
        flutter-version: 3.27.3
        cache: true

    - name: Check Flutter version, get correct dependencies, and build
      working-directory: ./duet_application
      run: 
        flutter --version;
        rm pubspec.lock;
        flutter pub get;
        flutter build web --release;
    
    - name: Upload Web Build Files
      uses: actions/upload-artifact@v4
      with:
        name: web-release
        path: ./duet_application/build/web