name: Web Build Check

on:
  push: 
    branches: [ "main" ]
<<<<<<< HEAD
  pull request:
=======
  pull_request:
>>>>>>> b330c96a2dd31076fc14c93b19833b1aaee1bb27
    branches: [ "main" ]

jobs:
  build:
    name: Test Web Build
    runs-on: ubuntu-latest
    steps:
    - name: Clone branch
      uses: actions/checkout@v4

    - name: Set Up Java
      uses: actions/setup-java@v3
      with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: gradle

    - name: Set Up Flutter
      uses: subosito/flutter-action@v2
      with: 
        channel: stable
<<<<<<< HEAD
        flutter-version: /duet_application/pubspec.yaml
        cache: true
      run: flutter --version
    
    - name: Get Dependencies
      run: flutter pub get

    - name: Start Web Release Build
      run: flutter build web --release
    
    - name: Upload Web Build Files
      uses: actions/upload-artifact@v2
      with:
        name: web-release
        path: ./duet_application/build/web
=======
        flutter-version: 3.27.3
        cache: true

    - name: Check Flutter version, get correct dependencies, and build
      working-directory: ./duet_application
      run: 
        flutter --version;
        rm pubspec.lock;
        flutter pub get;
        flutter build web --release;
    
    - name: Upload Web Build Files
      uses: actions/upload-artifact@v4
      with:
        name: web-release
        path: ./duet_application/build/web